#Плагин создан Limon_MineDel.
#LSRVBungeeCore - 1.0
#Команды:
#/find (Ник) - Поиск игрока
#/online или /online (сервер) - Узнать онлайн всего сервера или определённого
#/msg (получатель) (сообщение) - Отправить сообщение определённому игроку
#/alert (сообщение) - Отправить уведомление на весь сервер - lsrvbungeecore.alert
#/server (сервер) - Перейти на определённый сервер - lsrvbungeecore.server
#/hub или /lobby - Перейти на HUB сервер
#/mnt - Управление тех работами - lsrvbungeecore.maintenance
#/mnt on - Включить тех работы - lsrvbungeecore.maintenance
#/mnt off - Выключить тех работы - lsrvbungeecore.maintenance
#/mnt add (ник) - Добавить в список игроков которые смогут зайти во время тех работ - lsrvbungeecord.maintenance
#/mnt remove (ник) - Удалить из списка игроков которые смогут зайти во время тех работ - lsrvbungeecord.maintenance
#Зависимость в LuckPerms!!
hub: 'hub' #Сервер HUB (Главное лобби)
mysql: #Настройки MySQL
  login: 'root' #Имя пользователя
  password: 'root' #Пароль
  enable: false #Вкл/Выкл MySQL
  db: 'lsrv' #Имя датабазы
  ip: 'localhost' #IP базы данных
find: #Настройка команды /find
  leavetime: '&a&lИгрок {prefix} {nick} &a&lбыл в сети&f: &d&l{data}' #Если нет игрока на сервере, то будет сообщение с датой когда он последний раз был на сервере.
  online: '&a&lИгрок {prefix} {nick}  &a&lнаходится на сервере&f: &d&l{server}' #Если игрок на сервере, то будет сообщение с сервером где он находится.
  playernotfound: '&a&lДанный игрок некогда не играл на нашем проекте!' #Если игрок вообщее некогда не был на сервере
  usage: '{plugin-prefix} &c&lКоманда используется так&f: &a&l/find (ник)' #Использование команды
ping: '&aПинг игрока {prefix} {nick}&f: {ping}' #Сообщение при команде /ping
message: #Личные сообщения
  usage: '{plugin-prefix} &cКоманда используется так&f: &a/msg (ник) (сообщение)' #Использование команды
  my: '&aВы отправили сообщение игроку {prefix} {nick}&f: {message}' #Сообщение об отпраке сообщения
  from: '&aВы получили сообщение от игрока {prefix} {nick}&f: {message}' #Сообщение об получения сообщения
  noonline: '&cДанный игрок не онлайн!' #Сообщение если игрок не в сети
online: #Настройка команды /online
  online: '{plugin-prefix} &d&lОнлайн всего проекта&f: {online}' #Сообщение с онлайном всего сервера
  onlineserver: '{plugin-prefix} &d&lОнлайн сервера {server}&f: {online}' #Сообщение с онлайном определённого сервера
  servetnotfound: '{plugin-prefix} &c&lДанного сервера не существует' #Сообщение если такого сервера нету
server: #Настройка команды /server
  usage: '{plugin-prefix} &c&lКоманда используется так&f: &a&l/server (сервер)'
  servetnotfound: '{plugin-prefix} &c&lДанного сервера не существует' #Сообщение если такого сервера нету
  sendserver: '{plugin-prefix} &a&lВы подключились к серверу&f: &c{server}'
alert: #Настройка команды /alert
  mess: '&a&lУВЕДОМЛЕНИЕ&f: {message}'
  usage: '{plugin-prefix} &c&lКоманда используется так&f: &c&l/alert (сообщение)'
visual: #Визуальные настройки
  tab: #Настройка таба
    header: #Сверху
      - "&r"
      - "&6&lLSRVBungeeCore"
      - "&f"
      - "&fОбщий онлайн: §e%online%"
      - "&f"
    footer: #Снизу
      - "&r"
      - "      &fИгровой сервер: &e%server%      "
      - "&r"
      - "&fСайт: &6test.ru"
  motd: #Настройка MOTD
    header: '&a&lLSRVBungeeCore &f| Самый лучший сервер' #Сверху
    footer: '&b&lНаш сайт&f: &6&ltest.ru' #Снизу
    playerinfo: '&6&lЗАХОДИ И ИГРАЙ' #Табличка при наведении
    maintenance: #Настройка MOTD во время тех работ
      header: '&a&lLSRVBungeeCore &f| &c&lТЕХ РАБОТЫ' #Сверху
      footer: '&b&lВ данный момент на сервере тех работы' #Снизу
      playerinfo: '&a&lПодожди! На сервере тех работы' #Табличка при наведении
      kick-message: '&c&lВ данный момент на сервер нельзя зайти. На сервере тех работы!'
lang: #Языковые настройки
  noperm: '{plugin-prefix} &c&lУ вас нет прав!' #Сообщение когда нету прав
  prefix: '&a&lLSRVBungeeCore &f|' #Префикс сообщений
  maintenance: #Языковые настройки команд /mnt
    enabled: '{plugin-prefix} &a&lВы успешно включили режим тех работ на сервере!' #Сообщение при включении тех работ
    disabled: '{plugin-prefix} &a&lВы успешно выключили режим тех работ на сервере!' #Сообщение при выключении тех работ
    add: '&a&lВы успешно добавили игрока&f: &6&l{playername} в список доверенных' #Сообщение об успешном добавлении
    add-fail: '&c&lИгрок&f: &6&l{playername} уже состоит в списке доверенных!' #Сообщение об безуспешном добавлении
    remove: '&a&lВы успешно удалили игрока&f: &6&l{playername} из списка доверенных' #Сообщение об успешном удалении
    remove-fail: '&c&lИгрок&f: &6&l{playername} не состоит в списке доверенных!' #Сообщение об безуспешном удалении
    usage-add: '&6&l/mnt add (ник) - Добавить в список доверенных игроков' #Сообщение о том как использовать команду /add
    usage-remove: '&6&l/mnt remove (ник) - Удалить из списка доверенных  игроков' #Сообщение о том как использовать команду /remove
    help: #Команда помощи по тех работам
      - '{plugin-prefix} &c&lУправление тех работами&f:'
      - '&b&l/mnt on - Включить тех работы'
      - '&b&l/mnt off - Выключить тех работы'
      - '&6&l/mnt add (ник) - Добавить в список доверенных игроков'
      - '&6&l/mnt remove (ник) - Удалить из списка доверенных  игроков'